### PR TITLE
feat: add PGMAXLIFETIME env variable

### PR DESCRIPTION
**Pull request by Fishrock123**
Allows one to set the postgres pool max connection lifetime.

### CODE REVIEW

**Comment by Fishrock123** [comment]
(needs docs)

**Review by chrisdickinson — APPROVED** [review]
I have mixed feelings about this, mostly because node-postgres doesn't have an equivalent setting, instead relying on [idle timeout](https://docs.rs/sqlx/0.5.1/sqlx/pool/struct.PoolOptions.html#method.idle_timeout) / [node equiv](https://node-postgres.com/api/pool), which defaults to 10 seconds.

We _could_ make rust emulate node in this regard by setting `max_lifetime` to 0 while setting `idle_timeout` to 10 seconds. I believe setting `min_connections` to 1 would cause it to reconnect every 10 seconds. That seems a little silly, though?

It could be that `max_lifetime` makes more sense to use than `idle_timeout` here; I'd be interested in trying it out!

How's this sound for rollout? To start with we might set the max lifetime to something punishingly low on a dev cluster via config, then `siege` the server to see if we get an increased error rate (if, for example, pg conns get sniped out mid-execution.) If we don't see any errors or really obvious perf regressions then we can feel free to roll it out to prod.

**Comment by Fishrock123** [comment]
I strongly disagree that the options that `node-postgres` does or doesn't have should be our limiting factor here. It is still entirely _possible_ to have oversights there. We can change our default _and_ also support configuration for this, if desirable...

**Comment by Fishrock123** [comment]
From the SQLx discord ([link](https://discordapp.com/channels/665528275556106240/665528275556106243/832030389009645639)):

> [4:24 PM] abonander (DroidLogician): @Fishrock connection lifetime is only checked on release to and acquisition from the pool
> [4:24 PM] abonander (DroidLogician): and also periodically a background task will iterate the idle connections and reap any that have been idle too long or are past their max lifetime
> [4:40 PM] Fishrock: Does the background only check max_lifetime if the connection is idle?
> [4:55 PM] abonander (DroidLogician): yeah, when you acquire a connection you actually have ownership of it
> [4:55 PM] abonander (DroidLogician): PoolConnection is just an RAII wrapper that returns it to the pool afterward

**Pull request merged**
